# -*- coding: utf-8 -*-
"""Dictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mOvktrnAK3EEkOCq2mM5KuTGyiOBP7cO
"""

dicionario = {'curso': 'Python', 
              'time': 18,
              'preco': 59.99,
              1: 'um',
              'Nota': 10}
print(dicionario)

dicionario['curso']

a = dicionario['preco']
print(a)

# Edit a Key
dicionario['preco'] = 'R$89,90'
print(dicionario)

# Add new Key
dicionario['alunos'] = 50
print(dicionario)

# Check Dictionary Keys
dicionario.keys()

# Check Dictionary Values
dicionario.values()

# Check Dictionary Items
dicionario.items()

# Clear Dictionary Contents
dicionario.clear()
print(dicionario)