# -*- coding: utf-8 -*-
"""FloatIntLists.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iEUG-cTE-gc0qeUC70eJerNg7WUOP4oF
"""

num = 8
type(num)

float(num)

x = [2, 4, 10, 6]

nova = []
for item in x:
  nova.append(float(item))
print(nova)