# -*- coding: utf-8 -*-
"""Lambda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HOAdGsaFYVeZSLS8IH6yr2UDJ1b_op72
"""

# Declare a Function
def somaQuadrados(a, b):
  somaQ = a**2 + b**2
  return somaQ

# Call a Function
somaQuadrados(2, 3)

# Declare a Lambda Function (Função Anônina)
somaQuadrados2 = lambda a, b: a**2 + b**2

# Call a Function
somaQuadrados2(2, 3)

x = lambda f : f / 2

x(10)