# -*- coding: utf-8 -*-
"""ListComprehension.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18CGv9tz8df8-VaZdBo0sn-B0Y7evmQEz
"""

kmh = [40, 50, 56, 64, 73, 79, 85, 96, 100, 120]

# For
mph = []
for i in kmh:
  mph.append(i / 1.60934)
print(mph)

# Map
mph2 = list(map(lambda x : x / 1.60934, kmh))
print(mph2)

# List Comprehension
mph3 = [x / 1.60934 for x in kmh]
print(mph3)

caracteres = [i for i in 'Caracteres para varrer.']
print(caracteres)