# -*- coding: utf-8 -*-
"""Map.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ahjobhb7fqGK3HGsSkHUUyVgo9Spuagq
"""

kmh = [40, 50, 56, 64, 73, 79, 85, 96, 100, 120]

print(kmh)

mph = []
for i in kmh:
  mph.append(i / 1.60934)
print(mph)

mph2 = list(map(lambda x : x / 1.60934, kmh))
print(mph2)