# -*- coding: utf-8 -*-
"""MissingData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Eum70isWBCFVZ-ev3WWk6nBlULyxWwXS
"""

# Load Data
from google.colab import files
uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(name=fn,length=len(uploaded[fn])))

import pandas as pd
import io

dados = pd.read_csv(io.StringIO(uploaded['athlete_events.csv'].decode('utf-8')))

dados.head()

dados2 = dados.dropna()

dados2.head()

dados.shape

dados2.shape

enulo = dados.isnull()
#enulo.head(100)

faltantes = dados.isnull().sum()
print(faltantes)

faltantes_percentual = (dados.isnull().sum() / len(dados['ID']))*100
print(faltantes_percentual)

dados['Medal'].fillna('None', inplace = True)

dados['Age'].fillna(dados['Age'].mean(), inplace = True)

dados['Height'].fillna(dados['Height'].mean(), inplace = True)

dados['Weight'].fillna(dados['Weight'].mean(), inplace = True)

dados.head(100)