# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YfEdC_b-j9lrtMNyQ40CfhQNkDHVzfK8
"""

import numpy as np
a = np.array([1, 2, 3])
print(a)

b = np.array([(2, 5, 7), (5, 3, 9), (4, 6, 5)])
print(b)

c = np.zeros((4, 3))
print(c)

d = np.ones((5, 6))
print(d)

e = np.eye((4))
print(e)

b.max()

b.min()

b.sum()

b.mean()



b.std()

