# -*- coding: utf-8 -*-
"""PandasColumns2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Eum70isWBCFVZ-ev3WWk6nBlULyxWwXS
"""

# Load Data
from google.colab import files
uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(name=fn,length=len(uploaded[fn])))
#arquivo = "C:/ML/Vinhos/athlete_events.csv"

import pandas as pd
import io

dados = pd.read_csv(io.StringIO(uploaded['athlete_events.csv'].decode('utf-8')))

dados.head()

# Delete a column (axis = 0 -> linha; 1 -> coluna)
dados.drop('ID', axis= 1, inplace= True)
dados.drop('Season', axis= 1, inplace= True)
dados.drop('City', axis= 1, inplace= True)

dados.head()