# -*- coding: utf-8 -*-
"""PandasColumns.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Eum70isWBCFVZ-ev3WWk6nBlULyxWwXS
"""

# Load Data
from google.colab import files
uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(name=fn,length=len(uploaded[fn])))
#arquivo = "C:/ML/Vinhos/athlete_events.csv"

import pandas as pd
import io

dados = pd.read_csv(io.StringIO(uploaded['athlete_events.csv'].decode('utf-8')))

dados.head()

dados.rename(columns={'Name': 'Nome', 'Sex': 'Sexo', 'Age': 'Idade'}, inplace = True)

dados.head()

altura = dados['Height']

type(altura)

dados['Medal'].value_counts()

dados['City'].value_counts()

dados.describe()