# -*- coding: utf-8 -*-
"""Pandas2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N-Il6hCcePCtIQrSTwl2WlSVm3VXxRS3
"""

import pandas as pd
alunos = {'Nome': ['Ricardo', 'Pedro', 'Roberto', 'Carlos'], 
          'Nota': [4, 7, 5.5, 9],
          'Aprovado': ['Não', 'Sim', 'Não', 'Sim']}

# Convert a Dictionary to Dataset
dataframe = pd.DataFrame(alunos)

print(dataframe)

objeto1 = pd.Series([2, 6, 9, 10, 5])
print(objeto1)

import numpy as np
array1 = np.array([6, 12, 2, 9, 10])
array2 = np.array([(2, 6, 9, 10, 5), (6, 12, 2, 9, 10)])
print(array1)
print(array2)

objeto2 = pd.Series(array1)
print(objeto2)

# Esse comando da erro pq Series soh pode ser aplicado para dados unidimensionais
# objeto3 = pd.Series(array2)
# print(objeto3)