# -*- coding: utf-8 -*-
"""PandasRows.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RatTO0EE8BP6y4VHhwHcPSI14erlA4wy
"""

import pandas as pd
alunosDictionary = {'Nome': ['Ricardo', 'Pedro', 'Roberto', 'Carlos'], 
          'Nota': [4, 7, 5.5, 9],
          'Aprovado': ['Não', 'Sim', 'Não', 'Sim']}

alunosDataFrame = pd.DataFrame(alunosDictionary)

print(alunosDataFrame)

# Create a copy
alunosDataFrameTeste = alunosDataFrame

# Create New Dataframe
primeirasLinhas = alunosDataFrame.loc[0:2]
print(primeirasLinhas)

# Create by condition
novoDataFrame = alunosDataFrame.loc[ alunosDataFrame['Nota'] != 9  ]
print(novoDataFrame)

alunosReprovados = alunosDataFrame.loc[ alunosDataFrame['Aprovado'] != 'Sim' ]
print(alunosReprovados)