# -*- coding: utf-8 -*-
"""PandasFilter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ml0qdvmcBLV1FV9IkWFPoMhZS2-IdX37
"""

import pandas as pd
alunosDictionary = {'Nome': ['Ricardo', 'Pedro', 'Roberto', 'Carlos'], 
          'Nota': [4, 7, 5.5, 9],
          'Aprovado': ['Não', 'Sim', 'Não', 'Sim']}

alunosDataFrame = pd.DataFrame(alunosDictionary)

print(alunosDataFrame)

# Filter a column
alunosDataFrame['Aprovado']

# Filter a row
alunosDataFrame.loc[[1]]

alunosDataFrame.loc[[0, 3]]

alunosDataFrame.loc[1:3]

alunosDataFrame.loc[ alunosDataFrame['Nome'] == 'Pedro' ]