# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vC1u1ubIZp8WwzVVNV1wNi378FZAtxKl
"""

# No Jupyter
# import pandas as pd
# teste = pd.read_excel('C:/ML/Vinhos/arquivo1.xlsx')

# No Google Colab
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

import pandas as pd
import io

dados = pd.read_excel('arquivo1.xlsx')

dados.head(6)

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

dados2 = pd.read_csv('athlete_events.csv')