# -*- coding: utf-8 -*-
"""Strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bneSBXsbn3TvYkSokC5i5nztjRfK2Qyx
"""

frase = 'Exemplo de frase para testar Strings.'

frase[2]

frase[2:9]

frase[4:]

frase[:15]

frase[:]

# From 3 to 22 increasing 2 by 2
frase[3:23:2]

# Count elements
frase.count('a')

# Count blank spaces
frase.count(' ')

# Check the length
len(frase)

# Replace elements
frase.replace('para', 'pra')