# -*- coding: utf-8 -*-
"""Tuplas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yEsZjHukLAWokG7JOWAHivd92-eYRMZw
"""

lista = [2, 4, 7]

lista[0] = 20

print(lista)

# Tupple is an immutable list
tupla = (6, 8, 4)

tupla[0]

# This command will not work
# tupla[0] = 30

del lista[0]
print(lista)

# This command will not work
# del tupla[0]

# This command will not work
# tupla.append(10)

# Convert a List in a new Tupple
novaTupla = tuple(lista)
print(novaTupla)
type(novaTupla)

numero = (3)
type(numero)

numero2 = (3,)
type(numero2)